- name: Creating Backup Resources in SEA Region
  hosts: localhost
  connection: local
  collections:
  - azure.azcollection
  tasks:
  # Creating a Recovery Storage Vault
  - name: Create Azure Recovery Service vault
    azure_rm_recoveryservicesvault:
      resource_group: mknilavembu_sea
      name: seabkp
      location: australiaeast
      state: present
  ## Create Backup Policy
  - name: Create a daily VM backup policy
    azure_rm_backuppolicy:
      vault_name: Vault_Name
      name: Policy_Name
      resource_group: Resource_Group_Name
      state: present
      backup_management_type: "AzureIaasVM"
      schedule_run_frequency: "Daily"
      instant_recovery_snapshot_retention: 2
      daily_retention_count: 12
      time_zone: "Pacific Standard Time"
      schedule_run_time: 14  
  ## Enabling Backup for VM
  ### Webserver01
  - name: Get VM01 Fact
    azure_rm_virtualmachine_info:
      resource_group: mknilavembu_sea
      name: "webserver01"
    register: vm1
  - name: Enabling/Updating protection for the Azure Webserver01
    azure_rm_backupazurevm:
      resource_group: mknilavembu_sea
      recovery_vault_name: seabkp
      resource_id: "{{ vm1.vms.id }}"
      backup_policy_id: "{{ wbkp.id }}"
      state: 'create'
  ### Webserver02
  - name: Get VM02 Fact
    azure_rm_virtualmachine_info:
      resource_group: mknilavembu_sea
      name: "webserver02"
    register: vm2
  - name: Enabling/Updating protection for the Azure Webserver01
    azure_rm_backupazurevm:
      resource_group: mknilavembu_sea
      recovery_vault_name: seabkp
      resource_id: "{{ vm2.vms.id }}"
      backup_policy_id: "{{ wbkp.id }}"
      state: 'create'